<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Authors>ryi3r</Authors>
        <Copyright>ryi3r 2025</Copyright>
        <PackageId>Dialogue Helper</PackageId>
        <Product>Dialogue Helper</Product>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <PublishSingleFile>false</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.9" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
        <!--Condition
        below is needed to remove Avalonia.Diagnostics package from build output in Release
        configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageReference Include="LuaCSharp" Version="0.5.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Styles\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <Compile Remove="Styles\**" />
    </ItemGroup>
</Project>